export const state = () => [{
  color: '红色',
  button: "more+",
  href: "/produces/快时尚",
  image: "/images/image.jpg",
  subtitle: "快时尚 ",
  description: '稻城女款单层冲锋衣 OSY-TEX高度防水透气薄膜面料,精密磨砂质感方格图案表面;YKK 耐用顺滑高端拉链;全衣3D立体裁剪;全',
  title: '标题',
  etitle: "Fast fashion",
},
  {
    color: '红色',
    button: "more+",
    href: "/produces/快时尚",
    image: "/images/image2.jpg",
    subtitle: "快时尚 ",
    description: '稻城女款单层冲锋衣 OSY-TEX高度防水透气薄膜面料,精密磨砂质感方格图案表面;YKK 耐用顺滑高端拉链;全衣3D立体裁剪;全',
    title: '标题',
    etitle: "Fast fashion",
  },
  {
    color: '红色',
    button: "more+",
    href: "/produces/快时尚",
    image: "/images/image3.jpg",
    subtitle: "快时尚 ",
    description: '稻城女款单层冲锋衣 OSY-TEX高度防水透气薄膜面料,精密磨砂质感方格图案表面;YKK 耐用顺滑高端拉链;全衣3D立体裁剪;全',
    title: '标题',
    etitle: "Fast fashion",
  }
]
